// Generated by scripts/build-packs.mjs from the published catalog.
// Do not edit by hand — re-run `npm run build:packs` instead.

export interface CatalogPack {
  id: string;
  name: string;
  author: string;
  releaseYear: number | null;
  soundCount: number;
  previewUrl: string | null;
  family: 'system' | 'win7themes' | 'vistathemes' | 'plus';
  coverUrl: string | null;
  gradientFrom: string;
  gradientTo: string;
}

export const PACKS: CatalogPack[] = [
  {
    "id": "xp-real",
    "name": "Windows XP",
    "author": "Microsoft",
    "releaseYear": 2001,
    "soundCount": 17,
    "previewUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/xp-real/Windows%20XP%20Logon%20Sound.wav",
    "family": "system",
    "coverUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/xp-real/cover.jpg",
    "gradientFrom": "#4180c8",
    "gradientTo": "#1c205f"
  },
  {
    "id": "vista",
    "name": "Windows Vista",
    "author": "Microsoft",
    "releaseYear": 2006,
    "soundCount": 20,
    "previewUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/vista/Windows%20Logon%20Sound.wav",
    "family": "system",
    "coverUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/vista/cover.jpg",
    "gradientFrom": "#416ec8",
    "gradientTo": "#201c5f"
  },
  {
    "id": "win7",
    "name": "Windows 7",
    "author": "Microsoft",
    "releaseYear": 2009,
    "soundCount": 20,
    "previewUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/win7/Windows%20Logon%20Sound.wav",
    "family": "system",
    "coverUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/win7/cover.jpg",
    "gradientFrom": "#4190c8",
    "gradientTo": "#1c285f"
  },
  {
    "id": "win98",
    "name": "Windows 98",
    "author": "Microsoft",
    "releaseYear": 1998,
    "soundCount": 15,
    "previewUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/win98/start.wav",
    "family": "system",
    "coverUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/win98/cover.jpg",
    "gradientFrom": "#4173c8",
    "gradientTo": "#1e1c5f"
  },
  {
    "id": "win10",
    "name": "Windows 10",
    "author": "Microsoft",
    "releaseYear": 2015,
    "soundCount": 11,
    "previewUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/win10/Windows%20Logon.wav",
    "family": "system",
    "coverUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/win10/cover.jpg",
    "gradientFrom": "#41adc8",
    "gradientTo": "#1c365f"
  },
  {
    "id": "win8",
    "name": "Windows 8",
    "author": "Microsoft",
    "releaseYear": 2012,
    "soundCount": 7,
    "previewUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/win8/Windows%20Background.wav",
    "family": "system",
    "coverUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/win8/cover.jpg",
    "gradientFrom": "#41c8c3",
    "gradientTo": "#1c465f"
  },
  {
    "id": "win7-afternoon",
    "name": "Afternoon",
    "author": "Microsoft",
    "releaseYear": 2009,
    "soundCount": 14,
    "previewUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/win7-afternoon/Windows%20Logon%20Sound.wav",
    "family": "win7themes",
    "coverUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/win7-afternoon/cover.jpg",
    "gradientFrom": "#4190c8",
    "gradientTo": "#1c285f"
  },
  {
    "id": "plusxp-aquarium",
    "name": "Aquarium",
    "author": "Microsoft",
    "releaseYear": 2001,
    "soundCount": 15,
    "previewUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/plusxp-aquarium/Aquarium%20SysStart.wav",
    "family": "plus",
    "coverUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/plusxp-aquarium/cover.jpg",
    "gradientFrom": "#c8ab41",
    "gradientTo": "#535f1c"
  },
  {
    "id": "win7-calligraphy",
    "name": "Calligraphy",
    "author": "Microsoft",
    "releaseYear": 2009,
    "soundCount": 14,
    "previewUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/win7-calligraphy/Windows%20Logon%20Sound.wav",
    "family": "win7themes",
    "coverUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/win7-calligraphy/cover.jpg",
    "gradientFrom": "#41afc8",
    "gradientTo": "#1c385f"
  },
  {
    "id": "win7-characters",
    "name": "Characters",
    "author": "Microsoft",
    "releaseYear": 2009,
    "soundCount": 14,
    "previewUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/win7-characters/Windows%20Logon%20Sound.wav",
    "family": "win7themes",
    "coverUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/win7-characters/cover.jpg",
    "gradientFrom": "#4194c8",
    "gradientTo": "#1c2a5f"
  },
  {
    "id": "win7-cityscape",
    "name": "Cityscape",
    "author": "Microsoft",
    "releaseYear": 2009,
    "soundCount": 14,
    "previewUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/win7-cityscape/Windows%20Logon%20Sound.wav",
    "family": "win7themes",
    "coverUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/win7-cityscape/cover.jpg",
    "gradientFrom": "#41a4c8",
    "gradientTo": "#1c325f"
  },
  {
    "id": "plusxp-davinci",
    "name": "daVinci",
    "author": "Microsoft",
    "releaseYear": 2001,
    "soundCount": 15,
    "previewUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/plusxp-davinci/daVinci%20SysStart.wav",
    "family": "plus",
    "coverUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/plusxp-davinci/cover.jpg",
    "gradientFrom": "#c8bf41",
    "gradientTo": "#485f1c"
  },
  {
    "id": "win7-delta",
    "name": "Delta",
    "author": "Microsoft",
    "releaseYear": 2009,
    "soundCount": 14,
    "previewUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/win7-delta/Windows%20Logon%20Sound.wav",
    "family": "win7themes",
    "coverUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/win7-delta/cover.jpg",
    "gradientFrom": "#41bdc8",
    "gradientTo": "#1c3e5f"
  },
  {
    "id": "win7-festival",
    "name": "Festival",
    "author": "Microsoft",
    "releaseYear": 2009,
    "soundCount": 14,
    "previewUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/win7-festival/Windows%20Logon%20Sound.wav",
    "family": "win7themes",
    "coverUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/win7-festival/cover.jpg",
    "gradientFrom": "#41bdc8",
    "gradientTo": "#1c3e5f"
  },
  {
    "id": "win7-garden",
    "name": "Garden",
    "author": "Microsoft",
    "releaseYear": 2009,
    "soundCount": 14,
    "previewUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/win7-garden/Windows%20Logon%20Sound.wav",
    "family": "win7themes",
    "coverUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/win7-garden/cover.jpg",
    "gradientFrom": "#41a0c8",
    "gradientTo": "#1c305f"
  },
  {
    "id": "vista-glass",
    "name": "Glass",
    "author": "Microsoft",
    "releaseYear": 2006,
    "soundCount": 17,
    "previewUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/vista-glass/start.wav",
    "family": "vistathemes",
    "coverUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/vista-glass/cover.jpg",
    "gradientFrom": "#414ac8",
    "gradientTo": "#321c5f"
  },
  {
    "id": "win7-heritage",
    "name": "Heritage",
    "author": "Microsoft",
    "releaseYear": 2009,
    "soundCount": 14,
    "previewUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/win7-heritage/Windows%20Logon%20Sound.wav",
    "family": "win7themes",
    "coverUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/win7-heritage/cover.jpg",
    "gradientFrom": "#41adc8",
    "gradientTo": "#1c365f"
  },
  {
    "id": "plus95-jungle",
    "name": "Jungle",
    "author": "Microsoft",
    "releaseYear": 1995,
    "soundCount": 15,
    "previewUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/plus95-jungle/Jungle%20Windows%20Start.wav",
    "family": "plus",
    "coverUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/plus95-jungle/cover.jpg",
    "gradientFrom": "#c87541",
    "gradientTo": "#5f501c"
  },
  {
    "id": "win7-landscape",
    "name": "Landscape",
    "author": "Microsoft",
    "releaseYear": 2009,
    "soundCount": 14,
    "previewUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/win7-landscape/Windows%20Logon%20Sound.wav",
    "family": "win7themes",
    "coverUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/win7-landscape/cover.jpg",
    "gradientFrom": "#41a4c8",
    "gradientTo": "#1c325f"
  },
  {
    "id": "plus95-musica",
    "name": "Musica",
    "author": "Microsoft",
    "releaseYear": 1995,
    "soundCount": 15,
    "previewUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/plus95-musica/Musica%20Windows%20Start.wav",
    "family": "plus",
    "coverUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/plus95-musica/cover.jpg",
    "gradientFrom": "#c88541",
    "gradientTo": "#5f581c"
  },
  {
    "id": "plusxp-nature",
    "name": "Nature",
    "author": "Microsoft",
    "releaseYear": 2001,
    "soundCount": 15,
    "previewUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/plusxp-nature/Nature%20SysStart.wav",
    "family": "plus",
    "coverUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/plusxp-nature/cover.jpg",
    "gradientFrom": "#c8a241",
    "gradientTo": "#575f1c"
  },
  {
    "id": "vista-pearl",
    "name": "Pearl",
    "author": "Microsoft",
    "releaseYear": 2006,
    "soundCount": 19,
    "previewUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/vista-pearl/Windows%20Logon%20Sound.wav",
    "family": "vistathemes",
    "coverUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/vista-pearl/cover.jpg",
    "gradientFrom": "#4158c8",
    "gradientTo": "#2b1c5f"
  },
  {
    "id": "win7-quirky",
    "name": "Quirky",
    "author": "Microsoft",
    "releaseYear": 2009,
    "soundCount": 14,
    "previewUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/win7-quirky/Windows%20Logon%20Sound.wav",
    "family": "win7themes",
    "coverUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/win7-quirky/cover.jpg",
    "gradientFrom": "#416ec8",
    "gradientTo": "#201c5f"
  },
  {
    "id": "win7-raga",
    "name": "Raga",
    "author": "Microsoft",
    "releaseYear": 2009,
    "soundCount": 14,
    "previewUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/win7-raga/Windows%20Logon%20Sound.wav",
    "family": "win7themes",
    "coverUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/win7-raga/cover.jpg",
    "gradientFrom": "#41a9c8",
    "gradientTo": "#1c345f"
  },
  {
    "id": "plus95-robotz",
    "name": "Robotz",
    "author": "Microsoft",
    "releaseYear": 1995,
    "soundCount": 15,
    "previewUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/plus95-robotz/Robotz%20Windows%20Start.wav",
    "family": "plus",
    "coverUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/plus95-robotz/cover.jpg",
    "gradientFrom": "#c85841",
    "gradientTo": "#5f421c"
  },
  {
    "id": "win7-savanna",
    "name": "Savanna",
    "author": "Microsoft",
    "releaseYear": 2009,
    "soundCount": 14,
    "previewUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/win7-savanna/Windows%20Logon%20Sound.wav",
    "family": "win7themes",
    "coverUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/win7-savanna/cover.jpg",
    "gradientFrom": "#41bdc8",
    "gradientTo": "#1c3e5f"
  },
  {
    "id": "win7-sonata",
    "name": "Sonata",
    "author": "Microsoft",
    "releaseYear": 2009,
    "soundCount": 14,
    "previewUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/win7-sonata/Windows%20Logon%20Sound.wav",
    "family": "win7themes",
    "coverUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/win7-sonata/cover.jpg",
    "gradientFrom": "#41b4c8",
    "gradientTo": "#1c3a5f"
  },
  {
    "id": "plusxp-space",
    "name": "Space",
    "author": "Microsoft",
    "releaseYear": 2001,
    "soundCount": 15,
    "previewUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/plusxp-space/Space%20SysStart.wav",
    "family": "plus",
    "coverUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/plusxp-space/cover.jpg",
    "gradientFrom": "#c8a041",
    "gradientTo": "#585f1c"
  },
  {
    "id": "vista-tinker",
    "name": "Tinker",
    "author": "Microsoft",
    "releaseYear": 2006,
    "soundCount": 19,
    "previewUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/vista-tinker/Windows%20Logon.wav",
    "family": "vistathemes",
    "coverUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/vista-tinker/cover.jpg",
    "gradientFrom": "#4155c8",
    "gradientTo": "#2c1c5f"
  },
  {
    "id": "plus95-utopia",
    "name": "Utopia",
    "author": "Microsoft",
    "releaseYear": 1995,
    "soundCount": 15,
    "previewUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/plus95-utopia/Utopia%20Windows%20Start.WAV",
    "family": "plus",
    "coverUrl": "https://pub-a7bb18fa003c4b529e764f1c308a7146.r2.dev/packs/plus95-utopia/cover.jpg",
    "gradientFrom": "#c87c41",
    "gradientTo": "#5f541c"
  }
];

export const PACK_COUNT = 30;
